(function (global) {
  const data = global.campaignData;
  const mode = global.campaignMode;
  const progressKey = mode.STORAGE_KEY;
  let selectedCharacter = data.characters[0].id;
  let selectedDifficulty = "normal";
  let selectedStage = 1;
  const progress = () => mode.loadProgress(localStorage.getItem(progressKey), data.characters);
  const saveProgress = value => localStorage.setItem(progressKey, JSON.stringify(value));
  const character = () => data.characters.find(item => item.id === selectedCharacter) || data.characters[0];
  const stage = () => data.stages[selectedStage - 1];
  const campaignDeck = item => {
    const element = item.elements[0] || "光";
    const tier = { base: "none", normal: "normal", advanced: "advanced", special: "special" };
    return { id: `campaign-${item.id}`, name: `${item.name}战役卡组`, characterId: item.id, characterName: item.name, characterTitle: item.title, race: item.race, profession: item.profession, level: 60, element, cards: mode.flattenDeck(item.deck).map((name, index) => cardGenerator.cardFromName(name, { category: index < 14 ? "base" : "skill", skillTier: tier[index < 14 ? "base" : index < 22 ? "normal" : index < 28 ? "advanced" : "special"], level: 60, elementBias: element, profile: combinedProfile(item.race, item.profession), id: `campaign-${item.id}-${index}` })) };
  };
  const enemyDeck = currentStage => { const source = DEFAULT_CHARACTER_TEMPLATES.find(item => item.name === currentStage.enemyName); const deck = source ? deckBuilder.createCharacterDeck(source) : deckBuilder.createDeck({ race: "龙族", profession: "战士", level: 60, element: "火", includeCustom: false }); deck.level = 60; deck.name = `${currentStage.enemyName}战役卡组`; deck.cards = deck.cards.map(card => cardGenerator.cardFromName(card.baseName || card.name, { category: card.category, skillTier: card.skillTier, level: 60, elementBias: card.element || "火", profile: combinedProfile(deck.race, deck.profession) })); return deck; };
  function renderCampaignHome() {
    const saved = progress();
    const current = saved.characters[selectedCharacter];
    uiRenderer.openModal("战役模式", `<p class="small-note">固定角色 · 连续关卡 · 本地进度</p><h3 style="margin:14px 0 8px">选择角色</h3><div class="campaign-grid">${data.characters.map(item => `<button type="button" class="campaign-card ${item.id === selectedCharacter ? "selected" : ""}" data-campaign-character="${item.id}"><h3>${item.name}</h3><div>${item.title} · ${item.race}</div><div>${item.elements.join(" / ")} · ${item.passive}</div><small>${item.playStyle}</small><p style="margin-top:6px">首章进度：${saved.characters[item.id].completed ? "已完成" : `第 ${saved.characters[item.id].unlockedStage} 关已解锁`}</p></button>`).join("")}</div><h3 style="margin:14px 0 8px">难度</h3><div class="campaign-grid">${Object.entries(data.difficulties).map(([id, value]) => `<button type="button" class="campaign-stage ${id === selectedDifficulty ? "selected" : ""}" data-campaign-difficulty="${id}"><b>${value.label}</b><small>生命 ×${value.hp} · 威力 ×${value.power}</small></button>`).join("")}</div><h3 style="margin:14px 0 8px">关卡路线</h3><div class="campaign-grid">${data.stages.map(item => `<button type="button" class="campaign-stage ${item.order === selectedStage ? "selected" : ""}" data-campaign-stage="${item.order}" ${item.order > current.unlockedStage ? "disabled" : ""}><h3>${item.order}. ${item.name}</h3><div>${item.enemyName}</div><small>${item.intent}</small></button>`).join("")}</div><div class="modal-actions"><button class="ghost" id="campaignResetBtn" type="button">重置进度</button><button class="ghost" id="campaignCloseBtn" type="button">取消</button><button id="campaignStartBtn" type="button">进入第${selectedStage}关</button></div>`, { modalClass: "campaign-modal", afterRender: bindCampaignHome });
  }
  function bindCampaignHome() {
    document.querySelectorAll("[data-campaign-character]").forEach(button => button.onclick = () => { selectedCharacter = button.dataset.campaignCharacter; renderCampaignHome(); });
    document.querySelectorAll("[data-campaign-difficulty]").forEach(button => button.onclick = () => { selectedDifficulty = button.dataset.campaignDifficulty; renderCampaignHome(); });
    document.querySelectorAll("[data-campaign-stage]").forEach(button => button.onclick = () => { selectedStage = Number(button.dataset.campaignStage); renderCampaignHome(); });
    document.getElementById("campaignCloseBtn").onclick = () => uiRenderer.closeModal();
    document.getElementById("campaignStartBtn").onclick = startCampaign;
    document.getElementById("campaignResetBtn").onclick = () => uiRenderer.openConfirm({ title: "重置战役进度？", message: "六名角色的首章进度和最近战斗记录都会清除。", confirmText: "确认重置", onConfirm: () => { saveProgress(mode.defaultProgress(data.characters)); selectedStage = 1; renderCampaignHome(); } });
  }
  function startCampaign() {
    const player = character(); const currentStage = stage(); const state = gameEngine.start(campaignDeck(player), enemyDeck(currentStage));
    state.gameMode = "campaign"; state.campaign = { characterId: player.id, stage: selectedStage, difficulty: selectedDifficulty, playerRing: 0, enemyRing: 0, resonanceUsed: false, costReduction: 0, intent: null, passiveTriggers: 0 };
    state.enemy.name = currentStage.enemyName; state.enemy.campaignStyle = currentStage.style;
    const difficulty = data.difficulties[selectedDifficulty]; const enemyMultiplier = currentStage.multiplier * difficulty.hp; state.enemy.maxHp = Math.round(state.enemy.maxHp * enemyMultiplier); state.enemy.hp = state.enemy.maxHp; state.enemy.drawPile.concat(state.enemy.hand).forEach(card => { card.power = Math.round(card.power * currentStage.multiplier * difficulty.power); });
    state.campaignStats = { rounds: 1, cards: 0, advanced: 0, special: 0, resonance: 0, damage: 0, healing: 0, shield: 0 };
    uiRenderer.closeModal(); uiRenderer.nav("battle"); uiRenderer.render(); renderCampaignHud(); showMulligan();
    audioManager.preload(); audioManager.play("ui-open");
  }
  function showMulligan() {
    const state = gameEngine.state; uiRenderer.openModal("开局换牌", `<p class="small-note">最多选择两张牌；确认后本场不能再次换牌。</p><div class="campaign-grid" id="mulliganCards">${state.player.hand.map(card => `<button type="button" class="campaign-card" data-mulligan="${card.instanceId}"><b>${card.name}</b><small>${card.element} · 费用 ${card.cost}</small></button>`).join("")}</div><div class="modal-actions"><button id="mulliganConfirm" type="button">确认换牌（0/2）</button></div>`, { modalClass: "campaign-modal", afterRender: () => { const selected = new Set(); document.querySelectorAll("[data-mulligan]").forEach(button => button.onclick = () => { if (!selected.has(button.dataset.mulligan) && selected.size >= 2) return; selected.has(button.dataset.mulligan) ? selected.delete(button.dataset.mulligan) : selected.add(button.dataset.mulligan); button.classList.toggle("selected", selected.has(button.dataset.mulligan)); document.getElementById("mulliganConfirm").textContent = `确认换牌（${selected.size}/2）`; }); document.getElementById("mulliganConfirm").onclick = () => { const indexes = state.player.hand.map((card, index) => selected.has(card.instanceId) ? index : -1).filter(index => index >= 0); const returned = indexes.map(index => state.player.hand[index]); state.player.hand = state.player.hand.filter((_, index) => !indexes.includes(index)); state.player.drawPile = shuffle(state.player.drawPile.concat(returned)); gameEngine.draw(state.player, indexes.length); uiRenderer.closeModal(); state.campaign.mulliganDone = true; uiRenderer.render(); renderCampaignHud(); }; } });
  }
  function renderCampaignHud() { const state = gameEngine.state; if (!state?.campaign) return; let hud = document.getElementById("campaignHud"); if (!hud) { hud = document.createElement("div"); hud.id = "campaignHud"; hud.className = "campaign-hud"; document.getElementById("battlefield")?.appendChild(hud); } const intent = state.campaign.intent || mode.intentFor(state.enemy.hand, state.enemy.energy, state.enemy.campaignStyle); state.campaign.intent = intent; hud.innerHTML = `<span>星环</span><span class="campaign-ring">${Array.from({ length: 6 }, (_, i) => `<i class="${i < state.campaign.playerRing ? "on" : ""}"></i>`).join("")}</span><button type="button" id="resonanceBtn" ${state.turn !== "player" || state.campaign.playerRing < 6 || state.campaign.resonanceUsed ? "disabled" : ""}>共鸣</button><span class="campaign-intent">敌方意图：${intent.type}</span>`; document.getElementById("resonanceBtn")?.addEventListener("click", openResonance); }
  function openResonance() { uiRenderer.openModal("星环共鸣", `<p class="small-note">选择一种效果，使用后星环清零；每回合只能使用一次。</p><div class="campaign-grid"><button class="campaign-stage" data-resonance="star"><h3>星耀</h3><small>下一张牌费用减少2，最低为0。</small></button><button class="campaign-stage" data-resonance="echo"><h3>回响</h3><small>抽2张牌并获得1点能量。</small></button><button class="campaign-stage" data-resonance="guard"><h3>守环</h3><small>获得最大生命12%的护盾。</small></button></div>`, { modalClass: "campaign-modal", afterRender: () => document.querySelectorAll("[data-resonance]").forEach(button => button.onclick = () => activateResonance(button.dataset.resonance)) }); }
  function activateResonance(type) { const state = gameEngine.state; if (!state?.campaign || state.campaign.playerRing < 6 || state.campaign.resonanceUsed) return; state.campaign.playerRing = 0; state.campaign.resonanceUsed = true; state.campaignStats.resonance += 1; if (type === "star") state.campaign.costReduction = 2; if (type === "echo") { gameEngine.draw(state.player, 2); state.player.energy = Math.min(state.player.maxEnergy, state.player.energy + 1); } if (type === "guard") state.player.shield += mode.resonanceShield(state.player.maxHp); gameEngine.log(`[星环共鸣] 玩家激活${type === "star" ? "星耀" : type === "echo" ? "回响" : "守环"}。`); uiRenderer.closeModal(); audioManager.play("resonance-activate"); uiRenderer.render(); renderCampaignHud(); }
  const originalPlayCard = gameEngine.playCard.bind(gameEngine);
  gameEngine.playCard = function (side, instanceId) { const state = this.state; const actor = state?.[side]; const card = actor?.hand.find(item => item.instanceId === instanceId); if (!card) return false; const before = side === "enemy" ? state.player.hp : state.enemy.hp; const oldCost = card.cost; if (side === "player" && state.campaign?.costReduction) card.cost = mode.resonanceCost(card.cost, state.campaign.costReduction); const result = originalPlayCard(side, instanceId); card.cost = oldCost; if (!result || !state.campaign) return result; const ring = card.category === "base" ? 1 : card.skillTier === "special" ? 3 : card.skillTier === "advanced" ? 2 : 1; state.campaign[side === "player" ? "playerRing" : "enemyRing"] = mode.addRingEnergy(state.campaign[side === "player" ? "playerRing" : "enemyRing"], ring); state.campaignStats.cards += side === "player" ? 1 : 0; if (side === "player" && card.skillTier === "advanced") state.campaignStats.advanced += 1; if (side === "player" && card.skillTier === "special") state.campaignStats.special += 1; if (side === "player") state.campaignStats.damage += Math.max(0, before - state.enemy.hp); state.campaign.costReduction = 0; audioManager.play(card.effectType === "heal" ? "heal" : card.effectType === "shield" ? "shield" : card.effectType === "summon" ? "summon" : card.skillTier === "special" ? "magic-impact" : "card-play"); renderCampaignHud(); return result; };
  const originalRender = uiRenderer.render.bind(uiRenderer); uiRenderer.render = function () { originalRender(); renderCampaignHud(); };
  const originalEndTurn = gameEngine.endTurn.bind(gameEngine); gameEngine.endTurn = function (side) { const result = originalEndTurn(side); if (this.state?.campaign) { if (side === "enemy") this.state.campaign.resonanceUsed = false; this.state.campaign.intent = null; renderCampaignHud(); } return result; };
  const waitForCombatIdle = () => new Promise(resolve => { const check = () => { if (!gameEngine.state || gameEngine.state.gameOver || (!gameEngine.state.actionLocked && !effectsRenderer._playLock && !hasPendingOverrides())) resolve(); else setTimeout(check, 40); }; check(); });
  aiController.takeTurn = async function () { const state = gameEngine.state; if (!state || state.gameOver || state.turn !== "enemy") return; await waitForCombatIdle(); while (gameEngine.state === state && !state.gameOver && state.turn === "enemy") { const card = this.chooseCard(state.enemy, state.player); if (!card) { gameEngine.resolveAction({ type: "endTurn", side: "enemy" }); return; } const played = gameEngine.resolveAction({ type: "playCard", side: "enemy", cardInstanceId: card.instanceId }); if (!played) { await waitForCombatIdle(); continue; } await waitForCombatIdle(); } };
  document.querySelectorAll("[data-open-campaign]").forEach(button => button.addEventListener("click", renderCampaignHome));
  const campaignButton = document.createElement("button"); campaignButton.className = "campaign-home-button"; campaignButton.type = "button"; campaignButton.dataset.openCampaign = "true"; campaignButton.textContent = "✦ 战役模式 · 固定角色 / 连续关卡"; document.querySelector(".home-title-screen")?.appendChild(campaignButton); campaignButton.addEventListener("click", renderCampaignHome);
  const originalShowResult = uiRenderer.showResult.bind(uiRenderer); uiRenderer.showResult = function () { if (!gameEngine.state?.campaign) return originalShowResult(); const state = gameEngine.state; const won = state.winner === "player"; saveProgress(won ? mode.recordStageWin(progress(), state.campaign.characterId, state.campaign.stage) : mode.recordStageLoss(progress(), state.campaign.characterId)); const score = mode.scoreBattle({ victory: won, hpRatio: state.player.hp / state.player.maxHp, damageTakenRatio: 1 - state.player.hp / state.player.maxHp, rounds: state.round, difficulty: state.campaign.difficulty }); this.nav("result"); document.getElementById("resultTitle").textContent = won ? `战役胜利 · ${score}级评价` : `战役失败 · ${score}级评价`; document.getElementById("resultText").textContent = `${state.campaign.stage} · ${data.stages[state.campaign.stage - 1].name} · ${data.difficulties[state.campaign.difficulty].label}`; document.getElementById("resultStats").innerHTML = [["回合数", state.round],["剩余生命", formatNumber(state.player.hp)],["造成伤害", formatNumber(state.campaignStats.damage)],["使用卡牌", state.campaignStats.cards],["高级技能", state.campaignStats.advanced],["特殊技能", state.campaignStats.special],["星环共鸣", state.campaignStats.resonance],["评价", score]].map(([key, value]) => `<div class="stat-tile"><b>${value}</b><span>${key}</span></div>`).join(""); };
})(globalThis);
