(function (global) {
  const MAX_RING = 6;
  const STORAGE_KEY = "star-ring-campaign-progress-v1";
  function flattenDeck(deck) { return ["base", "normal", "advanced", "special"].flatMap(tier => deck[tier] || []); }
  function defaultProgress(characters) { return { version: 1, characters: Object.fromEntries(characters.map(c => [c.id, { unlockedStage: 1, completed: false }])), recentBattles: [] }; }
  function loadProgress(raw, characters) { try { return normalizeProgress(JSON.parse(raw || ""), characters); } catch { return defaultProgress(characters); } }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function recordStageWin(progress, characterId, stage) { const next = clone(progress); const entry = next.characters[characterId]; if (!entry) return next; entry.unlockedStage = Math.max(entry.unlockedStage, Math.min(5, stage + 1)); if (stage >= 5) entry.completed = true; return next; }
  function recordStageLoss(progress) { return clone(progress); }
  function mulligan(hand, indexes, replacement) { if (indexes.length > 2 || new Set(indexes).size !== indexes.length || indexes.some(i => i < 0 || i >= hand.length) || replacement.length !== indexes.length) throw new Error("换牌数量或位置无效"); const next = hand.slice(); indexes.forEach((index, i) => { next[index] = replacement[i]; }); return { hand: next, returned: indexes.map(index => hand[index]) }; }
  function addRingEnergy(value, amount) { return Math.min(MAX_RING, Math.max(0, value + amount)); }
  function resonanceCost(cost, reduction) { return Math.max(0, cost - reduction); }
  function resonanceShield(maxHp) { return Math.round(maxHp * .12); }
  function intentFor(cards, energy, style, context = {}) { const playable = cards.filter(card => Number(card.effectiveCost ?? card.cost) <= energy); if (!playable.length) return { type: "蓄力", card: null }; const card = playable.slice().sort((a, b) => aiCardScore(b, { ...context, style }) - aiCardScore(a, { ...context, style }))[0]; const type = card.skillTier === "special" ? "特殊技能" : card.skillTier === "advanced" ? "高级技能" : ["shield", "defense"].includes(card.effectType) ? "防御" : ["heal", "revive"].includes(card.effectType) ? "治疗" : ["control", "freeze"].includes(card.effectType) ? "控制" : "普通攻击"; return { type, card }; }
  function scoreBattle({ victory, hpRatio = 0, damageTakenRatio = 1, rounds = 99, difficulty = "normal" }) { if (!victory) return "C"; const bonus = difficulty === "hard" ? .12 : difficulty === "easy" ? -.04 : 0; const score = hpRatio * .45 + (1 - damageTakenRatio) * .3 + Math.max(0, 1 - rounds / 30) * .25 + bonus; return score >= .78 ? "S" : score >= .58 ? "A" : score >= .36 ? "B" : "C"; }
  function normalizeProgress(rawProgress, characters) { const fallback = defaultProgress(characters); const source = rawProgress && rawProgress.version === 1 && rawProgress.characters && typeof rawProgress.characters === "object" ? rawProgress : fallback; const normalized = defaultProgress(characters); characters.forEach(character => { const entry = source.characters[character.id]; if (!entry || typeof entry !== "object") return; const stage = Number(entry.unlockedStage); const completed = entry.completed === true || entry.completed === 1 || entry.completed === "true" || entry.completed === "yes"; normalized.characters[character.id] = { unlockedStage: Number.isFinite(stage) ? Math.min(5, Math.max(1, Math.round(stage))) : 1, completed }; }); normalized.recentBattles = Array.isArray(source.recentBattles) ? source.recentBattles.slice(0, 20) : []; return normalized; }
  function authorizeStage(progressEntry, stage) { return Number.isInteger(stage) && stage >= 1 && stage <= 5 && stage <= Number(progressEntry?.unlockedStage || 1); }
  function clampStage(progressEntry, stage) { return Math.min(5, Math.max(1, Math.min(Number(progressEntry?.unlockedStage || 1), Number(stage) || 1))); }
  function passiveAllowed(flags, characterId, scope) { const bucket = flags?.[scope] || {}; return !bucket[characterId]; }
  function consumePassive(flags, characterId, scope) { const next = clone(flags || {}); next[scope] = { ...(next[scope] || {}), [characterId]: true }; return next; }
  function enemyResonanceChoice({ hpRatio, playerThreat, hand, energy }) { if (hpRatio < .35 || playerThreat) return "guard"; if (hand.length < 3 || energy < 3) return "echo"; if (hand.some(card => ["advanced", "special"].includes(card.skillTier))) return "star"; return "guard"; }
  function shouldEnterBossPhase({ hpRatio, phaseTriggered }) { return !phaseTriggered && hpRatio < .5; }
  function recentBattles(existing, additions) { return additions.concat(existing).slice(0, 20); }
  function resultActions({ victory, stage }) { return victory && stage < 5 ? ["next", "retry", "route", "home"] : ["retry", "route", "home"]; }
  function effectiveCardCost(state, side, card) { const reduction = side === "player" ? state?.campaign?.costReduction || 0 : state?.campaign?.enemyCostReduction || 0; return Math.max(0, Number(card?.cost || 0) - reduction); }
  function expireResonance(state, side) { if (!state?.campaign) return; if (side === "player") state.campaign.costReduction = 0; if (side === "enemy") state.campaign.enemyCostReduction = 0; }
  function isFormalIntent(intent) { return Boolean(intent && typeof intent.type === "string" && typeof intent.cardInstanceId === "string" && typeof intent.description === "string" && Number.isFinite(Number(intent.generatedRound))); }
  function projectedEnergy(nextRound, maxEnergy, penalty = 0) { return Math.max(0, Math.min(maxEnergy, 3 + Math.floor(nextRound / 2) - penalty)); }
  function passiveTriggerState(characterId, flags, scope) { if (!passiveAllowed(flags, characterId, "match")) return null; return consumePassive(flags, characterId, "match"); }
  function aiCardScore(card, context = {}) { let score = Number(card.power || 0) / Math.max(1, Number(card.cost || 1)); const style = context.style; if (style === "curse" && ["curse", "debuff", "burn"].includes(card.effectType)) score *= 12; if (style === "curse" && context.playerHasCurse && ["attack", "execute", "pierce"].includes(card.effectType)) score *= 6; if (style === "control" && ["freeze", "control", "draw"].includes(card.effectType)) score *= 8; if (style === "control" && context.handSize < 3 && card.effectType === "draw") score *= 4; if (style === "aggressive" && ["attack", "pierce", "execute"].includes(card.effectType)) score *= context.playerLowHp ? 8 : 5; if (style === "guardian" && ["shield", "defense", "heal"].includes(card.effectType)) score *= 8; if (style === "guardian" && card.skillTier === "advanced") score *= 2; if (style === "adaptive") { if (context.enemyLowHp && ["heal", "shield", "defense"].includes(card.effectType)) score *= 6; else if (context.playerLowHp && ["attack", "execute", "pierce"].includes(card.effectType)) score *= 6; else if (context.enemyLowHp) score *= 3; } return score; }
  function createCombatStats() { return { damage: 0, highestDamage: 0, healing: 0, shield: 0, shieldAbsorbed: 0, elementalAdvantage: 0, passiveTriggers: 0, resonance: 0, enemyResonance: 0, summonDamage: 0, cards: 0, advanced: 0, special: 0, rounds: 0 }; }
  function recordCombatEvent(stats, event) { const amount = Math.max(0, Number(event.amount || 0)); if (event.type === "damage") { stats.damage += amount; stats.highestDamage = Math.max(stats.highestDamage, amount); if (event.summon) stats.summonDamage += amount; } if (event.type === "heal") stats.healing += amount; if (event.type === "shield") stats.shield += amount; if (event.type === "shieldAbsorbed") stats.shieldAbsorbed += amount; if (event.type === "elementalAdvantage") stats.elementalAdvantage += 1; if (event.type === "passive") stats.passiveTriggers += 1; if (event.type === "resonance") stats[event.side === "enemy" ? "enemyResonance" : "resonance"] += 1; }
  function drawCount(before, after) { return Math.max(0, Number(after) - Number(before)); }
  global.campaignMode = { MAX_RING, STORAGE_KEY, flattenDeck, defaultProgress, loadProgress, recordStageWin, recordStageLoss, mulligan, addRingEnergy, resonanceCost, resonanceShield, intentFor, scoreBattle, normalizeProgress, authorizeStage, clampStage, passiveAllowed, consumePassive, enemyResonanceChoice, shouldEnterBossPhase, recentBattles, resultActions, effectiveCardCost, expireResonance, isFormalIntent, projectedEnergy, passiveTriggerState, aiCardScore, createCombatStats, recordCombatEvent, drawCount };
})(globalThis);
