(function (global) {
  const data = global.campaignData;
  const mode = global.campaignMode;
  const campaignRules = global.campaignRules;
  const campaignRuntime = global.campaignRuntime;

  const escapeHtml = global.escapeHtml;
  const progressKey = mode.STORAGE_KEY;
  let selectedCharacter = data.characters[0].id;
  let selectedDifficulty = "normal";
  let selectedStage = 1;
  const CAMPAIGN_CHARACTER_MAP = { lisaya: "human-lisaya", luolinfo: "human-luolinfo", eluxia: "elf-eluxia", moluo: "orc-moluo", heka: "demon-heka", su: "godkin-su" };
  const difficulty = () => data.difficulties[selectedDifficulty] || data.difficulties.normal;
  const progress = () => { try { return mode.loadProgress(localStorage.getItem(progressKey), data.characters); } catch { return mode.defaultProgress(data.characters); } };
  const saveProgress = value => { try { localStorage.setItem(progressKey, JSON.stringify(value)); return true; } catch { return false; } };
  const character = () => data.characters.find(item => item.id === selectedCharacter) || data.characters[0];
  const stage = () => data.stages[selectedStage - 1];
  const campaignDeck = item => fixedCardLibrary.createRuntimeDeck(CAMPAIGN_CHARACTER_MAP[item.id]);
  const enemyDeck = currentStage => {
    const source = fixedCardLibrary.characterDefinitions.find(item => item.name === currentStage.enemyName) || fixedCardLibrary.charactersById["dragon-yemosu"];
    const deck = fixedCardLibrary.createRuntimeDeck(source.id);
    const tuning = difficulty();
    deck.maxHpMultiplier = tuning.hp;
    deck.cards = deck.cards.map(card => ({ ...card, effectMultiplier: tuning.power }));
    return deck;
  };
  function renderCampaignHome() {
    const saved = progress();
    const current = saved.characters[selectedCharacter];
    uiRenderer.openModal("战役模式", `<p class="small-note">固定角色 · 连续关卡 · 本地进度</p><p class="small-note">星环共鸣：每打出一张牌获得星环格；集满 6 格后，可在己方回合点击“共鸣”选择特殊效果。</p><h3 style="margin:14px 0 8px">选择角色</h3><div class="campaign-grid">${data.characters.map(item => `<button type="button" class="campaign-card ${item.id === selectedCharacter ? "selected" : ""}" data-campaign-character="${item.id}"><h3>${item.name}</h3><div>${item.title} · ${item.race}</div><div>世界观等级 ${item.loreLevel}</div><div>${item.elements.join(" / ")} · ${item.passive}</div><small>${item.playStyle}</small><p style="margin-top:6px">首章进度：${saved.characters[item.id].completed ? "已完成" : `第 ${saved.characters[item.id].unlockedStage} 关已解锁`}</p></button>`).join("")}</div><h3 style="margin:14px 0 8px">难度</h3><div class="campaign-grid">${Object.entries(data.difficulties).map(([id, value]) => `<button type="button" class="campaign-stage ${id === selectedDifficulty ? "selected" : ""}" data-campaign-difficulty="${id}"><b>${value.label}</b><small>生命 ×${value.hp} · 威力 ×${value.power}</small></button>`).join("")}</div><h3 style="margin:14px 0 8px">关卡路线</h3><div class="campaign-grid">${data.stages.map(item => `<button type="button" class="campaign-stage ${item.order === selectedStage ? "selected" : ""}" data-campaign-stage="${item.order}" ${item.order > current.unlockedStage ? "disabled" : ""}><h3>${item.order}. ${item.name}</h3><div>${item.enemyName}</div><small>${item.intent}</small></button>`).join("")}</div><div class="modal-actions"><button class="ghost" id="campaignResetBtn" type="button">重置进度</button><button class="ghost" id="campaignCloseBtn" type="button">取消</button><button id="campaignStartBtn" type="button" ${mode.authorizeStage(current, selectedStage) ? "" : "disabled"}>进入第${selectedStage}关</button></div>`, { modalClass: "campaign-modal", afterRender: bindCampaignHome });
  }
  function bindCampaignHome() {
    const recent = progress().recentBattles.slice(0, 5); if (recent.length) document.getElementById("modalBody")?.insertAdjacentHTML("beforeend", `<div class="campaign-recent"><h3 style="margin:14px 0 8px">最近战绩</h3>${recent.map(item => `<p class="small-note">${data.characters.find(character => character.id === item.characterId)?.name || "未知角色"} · 第${item.stage}关 · ${item.victory ? "胜利" : "失败"} · ${item.score} · ${item.rounds}回合</p>`).join("")}</div>`);
    document.querySelectorAll("[data-campaign-character]").forEach(button => button.onclick = () => { selectedCharacter = button.dataset.campaignCharacter; selectedStage = mode.clampStage(progress().characters[selectedCharacter], selectedStage); renderCampaignHome(); });
    document.querySelectorAll("[data-campaign-difficulty]").forEach(button => button.onclick = () => { selectedDifficulty = button.dataset.campaignDifficulty; renderCampaignHome(); });
    document.querySelectorAll("[data-campaign-stage]").forEach(button => button.onclick = () => { selectedStage = Number(button.dataset.campaignStage); renderCampaignHome(); });
    document.getElementById("campaignCloseBtn").onclick = () => uiRenderer.closeModal();
    document.getElementById("campaignStartBtn").onclick = startCampaign;
    document.getElementById("campaignResetBtn").onclick = () => uiRenderer.openConfirm({ title: "重置战役进度？", message: "六名角色的首章进度和最近战斗记录都会清除。", confirmText: "确认重置", onConfirm: () => { saveProgress(mode.defaultProgress(data.characters)); selectedStage = 1; renderCampaignHome(); } });
  }
  function startCampaign() {
    const player = character(); const currentStage = stage(); const state = gameEngine.start(campaignDeck(player), enemyDeck(currentStage));
    state.gameMode = "campaign"; state.campaign = { characterId: player.id, stage: selectedStage, difficulty: selectedDifficulty, playerRing: 0, enemyRing: 0, resonanceUsed: false, enemyResonanceUsed: false, costReduction: 0, enemyCostReduction: 0, intent: null, passiveTriggers: 0, passives: { turn: {}, match: {}, round: 0 } };
    state.enemy.name = currentStage.enemyName; state.enemy.campaignStyle = currentStage.style;
    const enemyEnergy = battleRules.roundEnergy(state.round, state.enemy.maxEnergy); const openingPlan = mode.intentFor(state.enemy.hand.map(card => ({ ...card, effectiveCost: mode.effectiveCardCost(state, "enemy", card) })), enemyEnergy, state.enemy.campaignStyle, { actor: state.enemy, target: state.player, playerLowHp: state.player.hp / state.player.maxHp < .3, enemyLowHp: state.enemy.hp / state.enemy.maxHp < .35, handSize: state.enemy.hand.length, playerHasCurse: state.player.statuses.some(status => status.type === "诅咒") }); state.campaign.intent = { type: openingPlan.type, cardInstanceId: openingPlan.card?.instanceId || "", description: `${state.enemy.name}正在准备${openingPlan.type}。`, generatedRound: state.round };
    // 难度倍率已写入敌方卡组和生命，玩家仍使用角色真实等级。
    state.campaignStats = state.combatStats;
    uiRenderer.closeModal(); uiRenderer.nav("battle"); uiRenderer.render(); renderCampaignHud(); showMulligan();
  }
  function showMulligan() {
    const state = gameEngine.state; uiRenderer.openModal("开局换牌", `<p class="small-note">最多选择两张牌；确认后本场不能再次换牌。</p><div class="campaign-grid" id="mulliganCards">${state.player.hand.map(card => `<button type="button" class="campaign-card" data-mulligan="${card.instanceId}"><b>${escapeHtml(card.name)}</b><small>${escapeHtml(card.element)} · 费用 ${escapeHtml(card.cost)}</small></button>`).join("")}</div><div class="modal-actions"><button id="mulliganConfirm" type="button">确认换牌（0/2）</button></div>`, { modalClass: "campaign-modal", afterRender: () => { const selected = new Set(); document.querySelectorAll("[data-mulligan]").forEach(button => button.onclick = () => { if (!selected.has(button.dataset.mulligan) && selected.size >= 2) return; selected.has(button.dataset.mulligan) ? selected.delete(button.dataset.mulligan) : selected.add(button.dataset.mulligan); button.classList.toggle("selected", selected.has(button.dataset.mulligan)); document.getElementById("mulliganConfirm").textContent = `确认换牌（${selected.size}/2）`; }); document.getElementById("mulliganConfirm").onclick = () => { const indexes = state.player.hand.map((card, index) => selected.has(card.instanceId) ? index : -1).filter(index => index >= 0); const returned = indexes.map(index => state.player.hand[index]); state.player.hand = state.player.hand.filter((_, index) => !indexes.includes(index)); gameEngine.draw(state.player, indexes.length); state.player.drawPile = shuffle(state.player.drawPile.concat(returned)); uiRenderer.closeModal(); state.campaign.mulliganDone = true; uiRenderer.render(); renderCampaignHud(); }; } });
  }
  function renderCampaignHud() { const state = gameEngine.state; if (!state?.campaign) { document.getElementById("campaignHud")?.remove(); return; } let hud = document.getElementById("campaignHud"); if (!hud) { hud = document.createElement("div"); hud.id = "campaignHud"; hud.className = "campaign-hud"; document.getElementById("battlefield")?.appendChild(hud); } const ring = value => Array.from({ length: 6 }, (_, i) => `<i class="${i < value ? "on" : ""}"></i>`).join(""); const intent = mode.isFormalIntent(state.campaign.intent) ? state.campaign.intent : null; const intentLabel = intent ? `${intent.type} · ${intent.description}` : "敌方正在重新评估"; hud.innerHTML = `<span>我</span><span class="campaign-ring">${ring(state.campaign.playerRing)}</span><span>敌</span><span class="campaign-ring">${ring(state.campaign.enemyRing)}</span><button type="button" id="resonanceBtn" ${state.turn !== "player" || state.player.skipAction || state.campaign.playerRing < 6 || state.campaign.resonanceUsed ? "disabled" : ""}>共鸣</button><span class="campaign-intent">敌方意图：${escapeHtml(intentLabel)}</span>`; document.getElementById("resonanceBtn")?.addEventListener("click", openResonance); }
  function openResonance() { uiRenderer.openModal("星环共鸣", `<p class="small-note">选择一种效果，使用后星环清零；每回合只能使用一次。</p><div class="campaign-grid"><button class="campaign-stage" data-resonance="star"><h3>星耀</h3><small>下一张牌费用减少2，最低为0。</small></button><button class="campaign-stage" data-resonance="echo"><h3>回响</h3><small>抽2张牌并获得1点能量。</small></button><button class="campaign-stage" data-resonance="guard"><h3>守环</h3><small>获得最大生命12%的护盾。</small></button></div>`, { modalClass: "campaign-modal", afterRender: () => document.querySelectorAll("[data-resonance]").forEach(button => button.onclick = () => activateResonance(button.dataset.resonance)) }); }
  function activateResonance(type) { const state = gameEngine.state; if (!state?.campaign || state.player.skipAction || state.campaign.playerRing < 6 || state.campaign.resonanceUsed) return; state.campaign.playerRing = 0; state.campaign.resonanceUsed = true; mode.recordCombatEvent(state.campaignStats, { type: "resonance", side: "player" }); if (type === "star") state.campaign.costReduction = 2; if (type === "echo") { gameEngine.draw(state.player, 2); state.player.energy = Math.min(state.player.maxEnergy, state.player.energy + 1); } if (type === "guard") { const shield = mode.resonanceShield(state.player.maxHp); state.player.shield += shield; mode.recordCombatEvent(state.campaignStats, { type: "shield", amount: shield }); } gameEngine.log(`[星环共鸣] 玩家激活${type === "star" ? "星耀" : type === "echo" ? "回响" : "守环"}。`); uiRenderer.closeModal(); audioManager.play("resonance-activate"); uiRenderer.render(); renderCampaignHud(); }
  function refreshEffectiveCardCosts() { const state = gameEngine.state; if (!state?.campaign) return; document.querySelectorAll("#playerHand .card").forEach(element => { const card = state.player.hand.find(item => item.instanceId === element.dataset.instanceId); if (!card) return; const cost = mode.effectiveCardCost(state, "player", card); element.classList.toggle("unplayable", state.turn !== "player" || cost > state.player.energy); element.dataset.effectiveCost = String(cost); const costElement = element.querySelector(".card-cost"); if (costElement) { costElement.textContent = String(cost); costElement.setAttribute("aria-label", `${cost} 能量`); if (cost !== card.cost) costElement.style.backgroundImage = "none"; } }); const canPlay = state.turn === "player" && state.player.hand.some(card => mode.effectiveCardCost(state, "player", card) <= state.player.energy); document.getElementById("endTurnBtn")?.classList.toggle("pulse", state.turn === "player" && !canPlay); }
  const renderBaseCardPreview = global.renderBaseCardPreview; renderCardPreview = function (card) { const state = gameEngine.state; if (!card) return renderBaseCardPreview(card); const effectiveCost = state?.campaign ? mode.effectiveCardCost(state, "player", card) : undefined; return renderBaseCardPreview(card, { effectiveCost }); };
  const renderBattleSurface = uiRenderer.renderBattleSurface.bind(uiRenderer); uiRenderer.render = function () { renderBattleSurface(); refreshEffectiveCardCosts(); renderCampaignHud(); };
  document.querySelectorAll("[data-open-campaign]").forEach(button => button.addEventListener("click", renderCampaignHome));
  document.querySelector(".home-mobile-btn-campaign")?.setAttribute("hidden", "");

  function clearCampaignUi() { document.getElementById("campaignHud")?.remove(); document.querySelectorAll(".campaign-passive-notice").forEach(node => node.remove()); }
  function campaignNotice(text) { uiRenderer.showToast(text); const banner = document.getElementById("skillBanner"); if (banner) { banner.textContent = text; banner.classList.add("show"); setTimeout(() => banner.classList.remove("show"), 1600); } }
  function showModeChooser() { uiRenderer.openModal("选择战斗模式", `<p class="small-note">开始战斗后选择本次玩法。首页入口保持不变。</p><div class="campaign-grid"><button type="button" class="campaign-stage" id="chooseSandbox"><h3>沙盒模式</h3><small>自由选择、生成和测试卡组。</small></button><button type="button" class="campaign-stage" id="chooseCampaign"><h3>战役模式</h3><small>固定角色、连续关卡、本地进度。</small></button></div>`, { modalClass: "campaign-modal", afterRender: () => { document.getElementById("chooseSandbox").onclick = () => { uiRenderer.closeModal(); uiRenderer.openBattlePrep(); }; document.getElementById("chooseCampaign").onclick = () => { uiRenderer.closeModal(); renderCampaignHome(); }; } }); }
  document.addEventListener("click", event => { const campaignButton = event.target.closest?.("[data-open-campaign]"); const sandboxButton = event.target.closest?.("[data-open-battle-prep]"); const homeActive = document.getElementById("screen-home")?.classList.contains("active"); if ((campaignButton || (sandboxButton && homeActive))) { event.preventDefault(); event.stopImmediatePropagation(); showModeChooser(); } }, true);

  const originalNav = uiRenderer.nav.bind(uiRenderer); uiRenderer.nav = function (name) { if (name === "home") clearCampaignUi(); return originalNav(name); };
  const originalSandboxStart = uiRenderer.startBattle.bind(uiRenderer); uiRenderer.startBattle = async function () { clearCampaignUi(); if (gameEngine.state?.campaign) gameEngine.invalidateBattle(); return originalSandboxStart(); };
  const originalStartCampaign = startCampaign;
  startCampaign = function () { const saved = progress(); const entry = saved.characters[selectedCharacter]; if (!entry || !data.stages[selectedStage - 1] || !mode.authorizeStage(entry, selectedStage)) { selectedStage = mode.clampStage(entry, selectedStage); uiRenderer.showToast("当前角色尚未解锁该关卡", "error"); renderCampaignHome(); return false; } setCombatInputLocked(false); clearHpDisplayOverrides(); pendingGameOverCheck.flag = false; resetBattleViewTransform(); clearCampaignUi(); return originalStartCampaign(); };
  document.addEventListener("visibilitychange", () => { if (document.hidden) audioManager.stop(); });
  global.campaignResultActions = function campaignResultActions(state, ui) { const row = document.querySelector("#screen-result .button-row"); if (!row) return; const won = state.winner === "player"; row.innerHTML = mode.resultActions({ victory: won, stage: state.campaign.stage }).map(action => `<button type="button" data-campaign-result="${action}">${action === "next" ? "下一关" : action === "retry" ? "重试本关" : action === "route" ? "返回战役路线" : "返回首页"}</button>`).join(""); row.querySelectorAll("[data-campaign-result]").forEach(button => button.onclick = () => { const action = button.dataset.campaignResult; if (action === "home") { ui.nav("home"); return; } if (action === "route") { renderCampaignHome(); return; } selectedStage = action === "next" ? Math.min(5, state.campaign.stage + 1) : state.campaign.stage; startCampaign(); }); };
  campaignRuntime.configurePresentation({
    renderHud: renderCampaignHud,
    notice: campaignNotice,
    playSound: name => audioManager.play(name),
    playDrawSound: () => audioManager.play("card-draw"),
  });
  campaignRuntime.install();
})(globalThis);
