plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}

def debugKeystorePath = System.getenv("ANDROID_DEBUG_KEYSTORE")
def debugKeystorePassword = System.getenv("ANDROID_DEBUG_KEYSTORE_PASSWORD")
def debugKeyAlias = System.getenv("ANDROID_DEBUG_KEY_ALIAS")
def debugKeyPassword = System.getenv("ANDROID_DEBUG_KEY_PASSWORD")

android {
    namespace = "com.seiya.starcardbattle"
    compileSdk = 34

    signingConfigs {
        if (debugKeystorePath) {
            debug {
                storeFile new File(debugKeystorePath)
                storePassword debugKeystorePassword
                keyAlias debugKeyAlias
                keyPassword debugKeyPassword
            }
        }
    }

    defaultConfig {
        applicationId = "com.seiya.starcardbattle"
        minSdk = 23
        targetSdk = 34
        versionCode = 7
        versionName = "1.2.2"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildTypes {
        debug {
            if (debugKeystorePath) {
                signingConfig signingConfigs.debug
            }
        }
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.11.0"
}
